# Use the official Nginx image as the base
FROM nginx:latest

# Set metadata labels
LABEL "author"="manishadornala11072@gmail.com" "creationdate"="july 11th"

# Define build arguments
ARG TFORM="1.5.2"
ARG PACK="1.9.1"

# Set environment variables
ENV AWS_ACCESS_KEY_ID="AKIAXDEJB7FIDZYQGQED"
ENV AWS_SECRET_ACCESS_KEY="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"
ENV AWS_DEFAULT_REGION="us-east-1"

# Install required packages and create a new user
RUN apt install -y net-tools &&
    apt install -y curl nano &&
    apt install -y unzip jq iputils-ping &&
    useradd testuser1
COPY index.html /usr/share/nginx/html/
COPY contact.html /usr/share/nginx/html/
COPY scorekeeper.js /usr/share/nginx/html/
ADD style.css /usr/share/nginx/html/
ADD https://releases.hashicorp.com/terraform/${TFORM}/terraform_${TFORM}_linux_amd64.zip .
ADD https://releases.hashicorp.com/packer/${PACK}/packer_${PACK}_linux_amd64.zip .
RUN unzip terraform_${TFORM}_linux_amd64.zip &&
    unzip packer_${PACK}_linux_amd64.zip &&
    mv terraform /usr/local/bin &&
    mv packer /usr/local/bin &&
    rm -rf *.zip && terraform version && packer version
EXPOSE 80 8080 8000
USER testuser1
CMD ["ping", "-c 3", "www.goggle.com"]
